//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SliceView.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_SliceViewTYPE               129
#define IDR_CHILDFRAME                  130
#define IDB_CONTRAST                    145
#define IDD_DLG_VOLSIZE                 147
#define IDD_DLG_BROWSE                  148
#define IDD_DLG_EXP_OPT                 149
#define IDD_COLLABORATION               150
#define IDD_SEG_DLG                     151
#define IDD_DLD_SEGEX                   152
#define IDD_DLG_REGIONGROW              153
#define IDD_DLG_AUTOSEGMENT             155
#define IDD_DLG_3DRG                    159
#define IDC_CMB_LAYOUT                  1000
#define IDB_BRIGHT                      1002
#define IDC_CHK_LINE                    1003
#define IDC_CHK_INFO                    1004
#define IDC_SLD_BRIGHT                  1006
#define IDC_SLD_CONTRAST                1007
#define IDC_ST_CONTRAST                 1011
#define IDC_RA_AUTO                     1012
#define IDC_RA_EQUAL                    1013
#define IDC_BUTTON2                     1017
#define IDC_CMD_RG3D                    1017
#define IDC_CX                          1018
#define IDC_CY                          1019
#define IDC_FOLDERPATH                  1019
#define IDC_CZ                          1020
#define IDC_CMD_BROWSE                  1020
#define IDC_FILE_LIST                   1021
#define IDC_CMD_DESELECTALL             1022
#define IDC_CMD_SELECTALL               1023
#define IDC_RADIO1                      1024
#define IDC_RADIO2                      1025
#define IDC_RD_EXOP                     1025
#define IDC_EDIT_IPADDRESS              1025
#define IDC_RAD_CUT                     1025
#define IDC_EDIT_USERID                 1026
#define IDC_RAD_SEG                     1026
#define IDC_BUTTON_CONNECT              1027
#define IDC_BUTTON_START                1028
#define IDC_BUTTON_CONTROL              1029
#define IDC_LIST_CANDIDATE              1030
#define IDC_LIST_COLLABORATION          1031
#define IDC_RADIO_LEAVE                 1032
#define IDC_RADIO_ATTEND1               1033
#define IDC_SEG_SLICEPOS                1034
#define IDC_SEG_CONSTRAST               1035
#define IDC_SEG_BIRGHT                  1036
#define IDC_SEG_THRESHOLD               1037
#define IDC_SEG_PREPROC                 1038
#define IDC_SEG_BINDEFAULT              1039
#define IDC_CMD_SAVEALLSLICES           1040
#define IDC_SEGEX_PATH                  1041
#define IDC_SEGEX_BROW                  1042
#define IDC_SEGEX_FILETYPE              1043
#define IDC_CMD_SAVESLICE               1044
#define IDC_CMD_SAVEVOL                 1045
#define IDC_RG_SLD_BRIGHT               1047
#define IDC_RG_SLD_CONTRAST             1048
#define IDC_RG_SLD_THRES                1049
#define IDC_RG_CMD_SAVESINGLE           1050
#define IDC_RG_CMD_SAVEALL              1051
#define IDC_RG_CMD_SAVEVOL              1052
#define IDC_RG_SLD_SLICE                1053
#define IDC_RG_CHK_PREPROC              1054
#define IDC_RG_CHK_DEF                  1055
#define IDC_RG_GRAYGRP                  1058
#define IDC_RG_SETTINGGRP               1059
#define IDC_LBL_BRIGHT                  1060
#define IDC_LBL_CONTRAST                1061
#define IDC_LBL_THRES                   1062
#define IDC_BR_100                      1064
#define IDC_BR_M100                     1065
#define IDC_CS_100                      1066
#define IDC_CS_M100                     1067
#define IDC_TH_MIN                      1068
#define IDC_TH_MAX                      1069
#define IDC_TH_CUR                      1070
#define IDC_RG_OPPGRP                   1071
#define IDC_TH_MINBTHRES                1071
#define IDC_TH_MAXBTHRES                1072
#define IDC_RG_CB_CUTMODE               1073
#define IDC_RG_LBL_CUTMED               1075
#define IDC_AU_ORGFRAME                 1077
#define IDC_AU_RESFRAME                 1078
#define IDC_AU_SLD_SLICE                1090
#define IDC_AU_GRAYGRP                  1091
#define IDC_AU_CHK_PREPROC              1092
#define IDC_AU_LBL_BRIGHT               1093
#define IDC_AU_SLD_BRIGHT               1094
#define IDC_AU_SLD_CONTRAST             1095
#define IDC_AU_LBL_CONTRAST             1096
#define IDC_AU_SETTINGGRP               1097
#define IDC_AU_CHK_DEF                  1098
#define IDC_AU_LBL_THRES                1099
#define IDC_AU_SLD_THRES                1100
#define IDC_AU_OPPGRP                   1101
#define IDC_AU_LBL_CUTMED               1103
#define IDC_AU_CB_CMODE                 1104
#define IDC_AU_CMD_SAVESINGLE           1105
#define IDC_AU_CMD_SAVEALL              1106
#define IDC_AU_CMD_SAVEVOL              1107
#define IDC_AU_RAD_SEG                  1109
#define IDC_AU_RAD_CUT                  1110
#define IDC_3DRG_ORGFRAME               1113
#define IDC_3DRG_RESFRAME               1114
#define IDC_3DRG_SLD_SLICE              1115
#define IDC_3DRG_GRAYGRP                1116
#define IDC_3DRG_CHK_PREPROC            1117
#define IDC_3DRG_SLD_BRIGHT             1118
#define IDC_3DRG_SLD_CONTRAST           1119
#define IDC_3DRG_SETTINGGRP             1120
#define IDC_3DRG_CHK_DEF                1121
#define IDC_3DRG_SLD_THRES              1122
#define IDC_3DRG_RAD_SEG                1123
#define IDC_3DRG_RAD_CUT                1124
#define IDC_3DRG_LBL_CUTMED             1125
#define IDC_3DRG_CB_CUTMODE             1126
#define IDC_3DRG_OPPGRP                 1127
#define IDC_3DRG_CMD_SAVESINGLE         1128
#define IDC_3DRG_CMD_SAVEALL            1129
#define IDC_3DRG_CMD_SAVEVOL            1130
#define IDC_3DRG_START                  1131
#define IDC_3DRG_STARSLICE              1132
#define IDC_3DRG_ENDSLICE               1133
#define IDC_3DRG_LBLSTART               1134
#define IDC_3DRG_LBLEND                 1135
#define IDC_3DRG_CHK_BOUND              1136
#define IDC_3DRG_BTHRES                 1138
#define IDC_3DRG_SLD_BTHRES             1139
#define IDC_LBL_CURTHRE                 1140
#define IDC_LBL_CURBTHRE                1140
#define ID_TOOLLABEL                    32772
#define ID_PLACEHOLDER0                 32772
#define ID_BUTTON32773                  32773
#define ID_PLACEHOLDER1                 32773
#define ID_PLACEHOLDER2                 32775
#define ID_PLACEHOLDER3                 32776
#define ID_PLACEHOLDER4                 32777
#define ID_VIEW_SLICEBAR                32778
#define ID_BUTTON32779                  32779
#define ID_FILE_IMPORTFILES             32780
#define ID_Menu                         32781
#define ID_FILE_EXPORTFILES             32782
#define ID_COLLABORATION_COLLABORATIONDIALOG 32783
#define ID_TOOLS_SEGMENTATION           32784
#define ID_SEGMENTTOOLS_CUTOUT          32785
#define ID_SEGMENTTOOLS_REGIONGROWING   32786
#define ID_SEGMENTTOOLS_AUTODETECTION   32787
#define ID_SEGMENTTOOLS_REGION          32788
#define ID_SEGMENTTOOLS_3DRESGIONGROWING 32789

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
